# Generated by Django 6.0.2 on 2026-02-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidelizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='puntos_generados',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
