# Generated by Django 6.0.2 on 2026-03-02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def crear_mesas_y_grupo_meseros(apps, schema_editor):
    Mesa = apps.get_model("fidelizacion", "Mesa")
    Group = apps.get_model("auth", "Group")

    Group.objects.get_or_create(name="Meseros")
    for numero in range(1, 21):
        Mesa.objects.get_or_create(numero=numero, defaults={"activa": True})


def eliminar_mesas_y_grupo_meseros(apps, schema_editor):
    Mesa = apps.get_model("fidelizacion", "Mesa")
    Group = apps.get_model("auth", "Group")

    Mesa.objects.all().delete()
    Group.objects.filter(name="Meseros").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("carta", "0001_initial"),
        ("fidelizacion", "0003_cliente_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mesa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero", models.PositiveIntegerField(unique=True)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["numero"],
            },
        ),
        migrations.AddField(
            model_name="pedido",
            name="actualizado",
            field=models.DateTimeField(auto_now=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pedido",
            name="creado_por",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="pedidos_creados", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="pedido",
            name="direccion_entrega",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="pedido",
            name="mesa",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="fidelizacion.mesa"),
        ),
        migrations.AddField(
            model_name="pedido",
            name="metodo_pago",
            field=models.CharField(choices=[("EFECTIVO", "Efectivo"), ("TARJETA", "Tarjeta"), ("TRANSFERENCIA", "Transferencia"), ("CONTRAENTREGA", "Contraentrega")], default="EFECTIVO", max_length=20),
        ),
        migrations.AddField(
            model_name="pedido",
            name="nombre_cliente",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="pedido",
            name="observaciones",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="telefono_contacto",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="cliente",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="fidelizacion.cliente"),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="puntos_generados",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="tipo",
            field=models.CharField(choices=[("LOCAL", "En el local"), ("DOMICILIO", "A domicilio")], max_length=20),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name="PedidoItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cantidad", models.PositiveIntegerField(default=1)),
                ("precio_unitario", models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ("pedido", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="fidelizacion.pedido")),
                ("producto", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="carta.producto")),
            ],
            options={
                "verbose_name": "item de pedido",
                "verbose_name_plural": "items de pedido",
            },
        ),
        migrations.RunPython(crear_mesas_y_grupo_meseros, eliminar_mesas_y_grupo_meseros),
    ]
