# Generated by Django 6.0.2 on 2026-03-02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fidelizacion", "0004_pedidos_local_domicilio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pedido",
            options={"ordering": ["-fecha"]},
        ),
    ]
